import Link from "next/link";
import Image from "next/image";
import { HeritageCategoryCard } from "@/components/cards/HeritageCategoryCard";
import { HeritageSubfieldCard } from "@/components/cards/HeritageSubfieldCard";
import { WorkshopExperienceCard } from "@/components/cards/WorkshopExperienceCard";
import { MOVABLE_HERITAGE_CATEGORIES, MOVABLE_HERITAGE_SUBFIELDS } from "@/lib/constants/heritageCategories";
import { FEATURED_WORKSHOP_EXPERIENCES } from "@/lib/constants/workshopExperiences";

export default function HomePage() {
 const subfields=MOVABLE_HERITAGE_SUBFIELDS.filter(x=>x.featured).slice(0,6);
 return <div className="home-page"><section className="home-hero home-hero--cinematic"><div className="miras-container home-hero__grid"><div className="home-hero__content"><p className="miras-eyebrow">Taşınabilir Kültürel Miras</p><h1 className="home-hero__title">Yaşayan kültürel mirası <span>keşfedin.</span></h1><p className="home-hero__description">Eserleri, ustaları, yerleri ve üretim geleneklerini aynı dijital dünyada araştırın.</p><form action="/ara" className="home-search"><input name="q" type="search" placeholder="Eser, kişi, yer veya teknik ara" aria-label="Koleksiyonda ara"/><button type="submit">Ara</button></form><div className="home-hero__actions"><Link href="/ara" className="home-primary-action">Arşivde ara</Link><Link href="/miras-yolculugu" className="home-secondary-action">Miras yolculuğuna başla</Link></div></div><div className="home-hero__visual"><Image src="/images/heritage-courtyard.png" alt="Tarihî avluda kültürel miras atölyeleri" fill priority sizes="(max-width: 900px) 100vw, 50vw"/></div></div></section><section className="featured-heritage-section"><div className="miras-container"><header className="featured-heritage-section__header"><div><p className="miras-eyebrow">Keşif alanları</p><h2 className="featured-heritage-section__title">Zanaatların <span>yaşayan atlası</span></h2></div><p className="featured-heritage-section__intro">Kültürel mirası üretim geleneğine göre keşfedin.</p></header><div className="heritage-subfield-grid">{subfields.map((item,index)=><HeritageSubfieldCard key={item.code} subfield={item} index={index}/>)}</div><div className="featured-heritage-section__footer"><Link href="/kategoriler" className="featured-heritage-section__all-link">Tüm alanları keşfet</Link></div></div></section><section className="miras-section"><div className="miras-container"><p className="miras-eyebrow">Kategoriler</p><h2>Üretim gelenekleri</h2><div className="heritage-category-grid">{MOVABLE_HERITAGE_CATEGORIES.map(category=><HeritageCategoryCard key={category.code} category={category}/>)}</div></div></section><section id="atolyeler" className="workshop-experiences-section"><div className="miras-container"><header className="workshop-experiences-section__header"><div><p className="miras-eyebrow">Atölye turları</p><h2 className="workshop-experiences-section__title">Üretimin içine <span>gir.</span></h2></div><p className="workshop-experiences-section__intro">Eserleri üretildikleri atmosfer içinde keşfedin.</p></header><div className="workshop-experiences-grid">{FEATURED_WORKSHOP_EXPERIENCES.map((experience,index)=><WorkshopExperienceCard key={experience.code} experience={experience} index={index}/>)}</div></div></section></div>;
}
