"use client";
import { useEffect, useState } from "react";
import { SearchResultCard, type SearchResultCardItem } from "@/components/search/SearchResultCard";
const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";
type Option = { id: string; label: string; count: number };
type Facets = { subfields: Option[]; materials: Option[]; techniques: Option[]; places: Option[] };
export default function SearchPage() {
 const [q,setQ]=useState(""); const [page,setPage]=useState(1); const [items,setItems]=useState<SearchResultCardItem[]>([]); const [total,setTotal]=useState(0); const [facets,setFacets]=useState<Facets|null>(null); const [filters,setFilters]=useState<Record<string,string>>({});
 useEffect(()=>{fetch(`${API}/api/public/facets`).then(r=>r.ok?r.json():null).then(setFacets).catch(()=>setFacets(null))},[]);
 useEffect(()=>{const p=new URLSearchParams({q,page:String(page),page_size:"24"}); Object.entries(filters).forEach(([k,v])=>v&&p.append(k,v)); fetch(`${API}/api/public/assets?${p}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{setTotal(data.total);setItems(data.items.map((x:{id:string;title:string;description?:string;image_url?:string})=>({id:x.id,entityType:"heritage_asset",title:x.title,description:x.description,href:`/eser/${x.id}`,image:x.image_url?{src:`${API}${x.image_url}`,alt:x.title}:undefined}))) }).catch(()=>{setItems([]);setTotal(0)})},[q,page,filters]);
 const choose=(k:string,v:string)=>{setFilters(s=>({...s,[k]:s[k]===v?"":v}));setPage(1)};
 const group=(title:string,key:string,values:Option[]=[])=><section className="search-filter-group search-filter-group--open"><div className="search-filter-group__content"><strong>{title}</strong>{values.map(v=><label className="search-filter-checkbox" key={v.id}><input type="checkbox" checked={filters[key]===v.id} onChange={()=>choose(key,v.id)}/><span className="search-filter-checkbox__label">{v.label} ({v.count})</span></label>)}</div></section>;
 return <main className="search-page"><section className="search-page__hero"><div className="miras-container"><p className="miras-eyebrow">Koleksiyon keşfi</p><h1>Gerçek miras kayıtlarında arayın</h1><input className="search-page__input" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Eser adı, kişi, yer, kimlik, malzeme veya teknik"/></div></section><section className="search-page__content"><div className="miras-container search-page__layout"><aside className="search-filters">{group("Tüm alt alanlar","subfield",facets?.subfields)}{group("Malzeme","material",facets?.materials)}{group("Teknik","technique",facets?.techniques)}{group("Tüm şehirler","place",facets?.places)}</aside><div className="search-results"><div className="search-results__toolbar"><strong>{total} sonuç bulundu</strong></div>{items.length?<div className="search-results__grid">{items.map(i=><SearchResultCard key={i.id} item={i}/>)}</div>:<p className="search-results__empty">Kayıt bulunamadı veya katalog servisine erişilemiyor.</p>}{total>24?<div className="search-results__pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>Önceki</button><span>Sayfa {page}</span><button disabled={page*24>=total} onClick={()=>setPage(page+1)}>Sonraki</button></div>:null}</div></div></section></main>;
}
